### PR TITLE
I think I did it

### PR DESCRIPTION
**Pull request by RyanTramel**
I made class div area smaller and gave it a 20% margin on the left and right sides. I also tried to space out the elements from each other so that while they're on a straight line their not all scrunched up next to each other. 

Let me know if I need to fix it again. I will re do this as many times as it takes.

### CODE REVIEW

**Comment by zmon** [comment]
Got it!  I will let you know when I have tested it and merged it.

On Tue, Dec 9, 2014 at 10:08 PM, Ryan notifications@github.com wrote:

> I made class div area smaller and gave it a 20% margin on the left and
> right sides. I also tried to space out the elements from each other so that
> while they're on a straight line their not all scrunched up next to each
> other.
> 
> Let me know if I need to fix it again. I will re do this as many times as
> 
> ## it takes.
> 
> You can merge this Pull Request by running
> 
>   git pull https://github.com/RyanTramel/kc_311dailybrief gh-pages
> 
> Or view, comment on, or merge it at:
> 
>   https://github.com/codeforkansascity/kc_311dailybrief/pull/17
> Commit Summary
> - Update index.html
> - Update base.css
> - Update base.css
> - Update base.css
> - Update base.css
> 
> File Changes
> - _M_ css/base.css
>   https://github.com/codeforkansascity/kc_311dailybrief/pull/17/files#diff-0
>   (15)
> - _M_ index.html
>   https://github.com/codeforkansascity/kc_311dailybrief/pull/17/files#diff-1
>   (1)
> 
> Patch Links:
> - https://github.com/codeforkansascity/kc_311dailybrief/pull/17.patch
> - https://github.com/codeforkansascity/kc_311dailybrief/pull/17.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codeforkansascity/kc_311dailybrief/pull/17.

## 

Paul Barham
If I am not helping, let me know what I can do to help.
816-679-8010

**Comment by zmon** [comment]
We do not want to change base.css since it is part of BootStrap.

Try something like
http://css.maxdesign.com.au/listutorial/horizontal_master.htm
I googled "css how to make list horizontal" to find that.  You will want to
put your CSS in index.html for now using the style tag

<style type="text/css">
Add style rules here
</style>

Also, the easiest  way I know of starting over is to delete your fork from
settings. Then go back to
https://github.com/codeforkansascity/kc_311dailybrief and fork it again.

Keep up the good effort.

Paul

On Tue, Dec 9, 2014 at 11:11 PM, Paul Barham paulb@savagesoft.com wrote:

> Got it!  I will let you know when I have tested it and merged it.
> 
> On Tue, Dec 9, 2014 at 10:08 PM, Ryan notifications@github.com wrote:
> 
> > I made class div area smaller and gave it a 20% margin on the left and
> > right sides. I also tried to space out the elements from each other so that
> > while they're on a straight line their not all scrunched up next to each
> > other.
> > 
> > Let me know if I need to fix it again. I will re do this as many times as
> > 
> > ## it takes.
> > 
> > You can merge this Pull Request by running
> > 
> >   git pull https://github.com/RyanTramel/kc_311dailybrief gh-pages
> > 
> > Or view, comment on, or merge it at:
> > 
> >   https://github.com/codeforkansascity/kc_311dailybrief/pull/17
> > Commit Summary
> > - Update index.html
> > - Update base.css
> > - Update base.css
> > - Update base.css
> > - Update base.css
> > 
> > File Changes
> > - _M_ css/base.css
> >   https://github.com/codeforkansascity/kc_311dailybrief/pull/17/files#diff-0
> >   (15)
> > - _M_ index.html
> >   https://github.com/codeforkansascity/kc_311dailybrief/pull/17/files#diff-1
> >   (1)
> > 
> > Patch Links:
> > - https://github.com/codeforkansascity/kc_311dailybrief/pull/17.patch
> > - https://github.com/codeforkansascity/kc_311dailybrief/pull/17.diff
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/codeforkansascity/kc_311dailybrief/pull/17.
> 
> ## 
> 
> Paul Barham
> If I am not helping, let me know what I can do to help.
> 816-679-8010

## 

Paul Barham
If I am not helping, let me know what I can do to help.
816-679-8010

**Comment by RyanTramel** [comment]
Thank you, I'll get on that tonight and see if I can fix it with what I
learn from the link.

On Wed, Dec 10, 2014 at 12:48 AM, zmon notifications@github.com wrote:

> We do not want to change base.css since it is part of BootStrap.
> 
> Try something like
> http://css.maxdesign.com.au/listutorial/horizontal_master.htm
> I googled "css how to make list horizontal" to find that. You will want to
> put your CSS in index.html for now using the style tag
> 
> <style type="text/css">
> Add style rules here
> </style>
> 
> Also, the easiest way I know of starting over is to delete your fork from
> settings. Then go back to
> https://github.com/codeforkansascity/kc_311dailybrief and fork it again.
> 
> Keep up the good effort.
> 
> Paul
> 
> On Tue, Dec 9, 2014 at 11:11 PM, Paul Barham paulb@savagesoft.com
> wrote:
> 
> > Got it! I will let you know when I have tested it and merged it.
> > 
> > On Tue, Dec 9, 2014 at 10:08 PM, Ryan notifications@github.com wrote:
> > 
> > > I made class div area smaller and gave it a 20% margin on the left and
> > > right sides. I also tried to space out the elements from each other so
> > > that
> > > while they're on a straight line their not all scrunched up next to
> > > each
> > > other.
> > > 
> > > Let me know if I need to fix it again. I will re do this as many times
> > > as
> > > 
> > > ## it takes.
> > > 
> > > You can merge this Pull Request by running
> > > 
> > > git pull https://github.com/RyanTramel/kc_311dailybrief gh-pages
> > > 
> > > Or view, comment on, or merge it at:
> > > 
> > > https://github.com/codeforkansascity/kc_311dailybrief/pull/17
> > > Commit Summary
> > > - Update index.html
> > > - Update base.css
> > > - Update base.css
> > > - Update base.css
> > > - Update base.css
> > > 
> > > File Changes
> > > - _M_ css/base.css
> > >   <
> > >   https://github.com/codeforkansascity/kc_311dailybrief/pull/17/files#diff-0>
> > > 
> > > (15)
> > > - _M_ index.html
> > >   <
> > >   https://github.com/codeforkansascity/kc_311dailybrief/pull/17/files#diff-1>
> > > 
> > > (1)
> > > 
> > > Patch Links:
> > > - https://github.com/codeforkansascity/kc_311dailybrief/pull/17.patch
> > > - https://github.com/codeforkansascity/kc_311dailybrief/pull/17.diff
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/codeforkansascity/kc_311dailybrief/pull/17.
> > 
> > ## 
> > 
> > Paul Barham
> > If I am not helping, let me know what I can do to help.
> > 816-679-8010
> 
> ## 
> 
> Paul Barham
> If I am not helping, let me know what I can do to help.
> 816-679-8010
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codeforkansascity/kc_311dailybrief/pull/17#issuecomment-66411303
> .

## 

Ryan Tramel
rytramel@gmail.com

**Comment by RyanTramel** [comment]
Probably tonight if not definitely tomorrow.

On Wed, Dec 10, 2014 at 5:27 PM, Ryan Tramel rytramel@gmail.com wrote:

> Thank you, I'll get on that tonight and see if I can fix it with what I
> learn from the link.
> 
> On Wed, Dec 10, 2014 at 12:48 AM, zmon notifications@github.com wrote:
> 
> > We do not want to change base.css since it is part of BootStrap.
> > 
> > Try something like
> > http://css.maxdesign.com.au/listutorial/horizontal_master.htm
> > I googled "css how to make list horizontal" to find that. You will want
> > to
> > put your CSS in index.html for now using the style tag
> > 
> > <style type="text/css">
> > Add style rules here
> > </style>
> > 
> > Also, the easiest way I know of starting over is to delete your fork from
> > settings. Then go back to
> > https://github.com/codeforkansascity/kc_311dailybrief and fork it again.
> > 
> > Keep up the good effort.
> > 
> > Paul
> > 
> > On Tue, Dec 9, 2014 at 11:11 PM, Paul Barham paulb@savagesoft.com
> > wrote:
> > 
> > > Got it! I will let you know when I have tested it and merged it.
> > > 
> > > On Tue, Dec 9, 2014 at 10:08 PM, Ryan notifications@github.com
> > > wrote:
> > > 
> > > > I made class div area smaller and gave it a 20% margin on the left and
> > > > right sides. I also tried to space out the elements from each other so
> > > > that
> > > > while they're on a straight line their not all scrunched up next to
> > > > each
> > > > other.
> > > > 
> > > > Let me know if I need to fix it again. I will re do this as many times
> > > > as
> > > > 
> > > > ## it takes.
> > > > 
> > > > You can merge this Pull Request by running
> > > > 
> > > > git pull https://github.com/RyanTramel/kc_311dailybrief gh-pages
> > > > 
> > > > Or view, comment on, or merge it at:
> > > > 
> > > > https://github.com/codeforkansascity/kc_311dailybrief/pull/17
> > > > Commit Summary
> > > > - Update index.html
> > > > - Update base.css
> > > > - Update base.css
> > > > - Update base.css
> > > > - Update base.css
> > > > 
> > > > File Changes
> > > > - _M_ css/base.css
> > > >   <
> > > >   https://github.com/codeforkansascity/kc_311dailybrief/pull/17/files#diff-0>
> > > > 
> > > > (15)
> > > > - _M_ index.html
> > > >   <
> > > >   https://github.com/codeforkansascity/kc_311dailybrief/pull/17/files#diff-1>
> > > > 
> > > > (1)
> > > > 
> > > > Patch Links:
> > > > - https://github.com/codeforkansascity/kc_311dailybrief/pull/17.patch
> > > > - https://github.com/codeforkansascity/kc_311dailybrief/pull/17.diff
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/codeforkansascity/kc_311dailybrief/pull/17.
> > > 
> > > ## 
> > > 
> > > Paul Barham
> > > If I am not helping, let me know what I can do to help.
> > > 816-679-8010
> > 
> > ## 
> > 
> > Paul Barham
> > If I am not helping, let me know what I can do to help.
> > 816-679-8010
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/codeforkansascity/kc_311dailybrief/pull/17#issuecomment-66411303
> > .
> 
> ## 
> 
> Ryan Tramel
> rytramel@gmail.com

## 

Ryan Tramel
rytramel@gmail.com

**Pull request closed without merging**
